spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/job-finder
    username: job-dev-user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #none | update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  redis:
    host: 127.0.0.1
    port: 6379
#    password: # Optional if Redis has no password
#      com.

#      logging.level.com.yourcompany=TRACE  


server:
  port: 8081
  servlet:
    context-path: /api

weather:
  api:
    base-url: http://api.weatherstack.com
    access-key: 3b706a649b98ecec69e400ef9ae3a0b0

# weather forecast api::     3b706a649b98ecec69e400ef9ae3a0b0

#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.password= # Optional if Redis has no password